name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: 'pip install -r requirements.txt'

      - name: install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: local install
        run: 'python setup.py install'

      - name: Tests
        run: 'bash scripts/test.sh'

      - name: Build
        run: 'bash scripts/build.sh'

      - name: Upload to test.pypi
        run: 'twine upload --repository-url https://test.pypi.org/legacy/ dist/*'
        env:
          TWINE_USERNAME: 'noelm'
          TWINE_PASSWORD: '${{ secrets.TWINE_PWD }}'
          TWINE_NON_INTERACTIVE: true

      - name: Upload to pypi
        run: 'twine upload dist/*'
        env:
          TWINE_USERNAME: 'noelm'
          TWINE_PASSWORD: '${{ secrets.TWINE_PWD }}'
          TWINE_NON_INTERACTIVE: true

      - name: Publish Github Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: dist/*
